AWSTemplateFormatVersion: 2010-09-09
Description: private-documents-signed-url
Transform:
- AWS::Serverless-2016-10-31
Resources:
  getSignedUrl:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-signed-url.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      CodeUri: s3://get-signed-url/ef54af9a8469d2ee8f020a5d6230a46e
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
